# Generated by Django 5.1.1 on 2024-10-20 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyUser',
            fields=[
                ('spotify_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('last_spotify_wrapped', models.JSONField(default=dict)),
            ],
        ),
    ]
