# Generated by Django 5.1.2 on 2024-11-29 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("read", "Read"),
                            ("responded", "Responded"),
                        ],
                        default="new",
                        max_length=10,
                    ),
                ),
                ("admin_response", models.TextField(blank=True, null=True)),
                ("admin_response_at", models.DateTimeField(blank=True, null=True)),
                (
                    "admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handled_feedbacks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Feedback",
                "verbose_name_plural": "Feedbacks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SpotifyUser",
            fields=[
                (
                    "spotify_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("user_name", models.CharField(max_length=255)),
                (
                    "profile_image",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("past_wraps", models.JSONField(default=list)),
                ("last_spotify_wrapped", models.JSONField(default=dict)),
                ("personality_description", models.TextField(blank=True, null=True)),
                ("wrapped_id", models.CharField(max_length=10, unique=True)),
                (
                    "friends",
                    models.ManyToManyField(blank=True, to="wrapped.spotifyuser"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpotifyAuth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.CharField(max_length=255)),
                ("refresh_token", models.CharField(max_length=255)),
                ("token_expiry", models.DateTimeField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wrapped.spotifyuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SavedWrap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("tracks_data", models.JSONField()),
                ("artists_data", models.JSONField()),
                ("genres_data", models.JSONField()),
                ("time_range", models.CharField(max_length=50)),
                (
                    "holiday_theme",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "personality_info",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("comp", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_wraps",
                        to="wrapped.spotifyuser",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
