# Generated by Django 5.1.1 on 2024-10-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyuser',
            name='friends',
            field=models.ManyToManyField(blank=True, to='wrapped.spotifyuser'),
        ),
        migrations.AddField(
            model_name='spotifyuser',
            name='past_wraps',
            field=models.JSONField(default=list),
        ),
    ]
