# Generated by Django 5.1.2 on 2024-11-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wrapped", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedwrap",
            name="friend_tracks_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
