# Generated by Django 5.1.1 on 2024-10-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped', '0002_spotifyuser_friends_spotifyuser_past_wraps'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyuser',
            name='profile_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
