# Generated by Django 5.1.2 on 2024-11-29 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wrapped", "0002_savedwrap_friend_tracks_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savedwrap",
            name="comp",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
