# Generated by Django 5.1.1 on 2024-10-31 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped', '0005_savedwrap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedwrap',
            name='holiday_theme',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='savedwrap',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_wraps', to='wrapped.spotifyuser'),
        ),
    ]
