# Generated by Django 5.1.1 on 2024-11-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped', '0006_alter_savedwrap_holiday_theme_alter_savedwrap_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
