# Generated by Django 5.1.1 on 2024-11-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped', '0006_alter_savedwrap_holiday_theme_alter_savedwrap_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyuser',
            name='wrapped_id',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]


