# Generated by Django 5.1.1 on 2024-11-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped', '0008_auto_20241119_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifyuser',
            name='wrapped_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
