# Generated by Django 5.1.1 on 2024-11-19 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped', '0008_spotifyauth'),
        ('wrapped', '0010_auto_20241119_1546'),
    ]

    operations = [
    ]
