# Generated by Django 5.1.2 on 2024-11-21 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wrapped", "0008_savedwrap_personality_info"),
        ("wrapped", "0011_merge_0008_spotifyauth_0010_auto_20241119_1546"),
    ]

    operations = []
