# Generated by Django 5.1.2 on 2024-11-21 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wrapped", "0012_merge_20241121_2309"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="spotifyuser",
            name="email",
        ),
        migrations.AddField(
            model_name="savedwrap",
            name="friend_tracks_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
