# Generated by Django 5.1.2 on 2024-11-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wrapped", "0014_savedwrap_comp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savedwrap",
            name="personality_info",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
